Repository Oneflow-Inc/libai, pull requests merged in 2022-03, with the labels that each got.

#157 add nlp get started
  docs/source/tutorials/Getting Started.md
Labels: documentation

#189 fix swin eager global training
  configs/swin_cifar100.py
  libai/engine/trainer.py
  libai/models/swin_transformer.py
Labels: bug

#187 add config tutorial
  configs/common/optim.py
  configs/common/train.py
  docs/source/index.rst
  docs/source/libai.models.rst
  docs/source/tutorials/Config_System.md
  libai/engine/default.py
  libai/layers/embedding.py
  libai/models/utils/graph_base.py
  libai/tokenizer/build.py
Labels: documentation

#194 Add dist config docs
  configs/vit_imagenet.py
  docs/source/index.rst
  docs/source/libai.models.rst
  docs/source/tutorials/Config_System.md
  docs/source/tutorials/Distributed_Configuration.md
  docs/source/tutorials/Getting_Started.md
  docs/source/tutorials/Installation.md
  docs/source/tutorials/Model_Zoo.md
  docs/source/tutorials/Train_and_Eval_Command_Line.md
  libai/layers/embedding.py
  libai/models/gpt_model.py
  libai/models/swin_transformer.py
  libai/models/t5_model.py
  libai/models/vision_transformer.py
  libai/optim/build.py
  libai/utils/distributed.py
  libai/utils/events.py
Labels: documentation

#190 Add New Project Tutorial
  docs/source/index.rst
  docs/source/tutorials/Build_New_Project_on_LiBai.md
Labels: documentation

#223 Update requirements.txt
  docs/requirements.txt
Labels: bug

#228 Fix line space
  docs/requirements.txt
  docs/source/_static/collapse.js_t
  docs/source/_static/css/line_space.css
  docs/source/_static/css/sidebar.css
  docs/source/_templates/layout.html
  docs/source/_templates/line_space.html
  docs/source/conf.py
Labels: bug, documentation
