Repository Oneflow-Inc/libai, pull requests merged in 2022-11, with the labels that each got.

#434 Fix bug that random init head.weight in eval mode
  projects/MAE/configs/mae_finetune.py
  projects/MAE/train_net.py
  projects/MAE/utils/weight_convert.py
Labels: bug, ready for review

#438 Docs: add auto_parallel interface document link
  docs/source/tutorials/basics/Auto_Parallel.md
Labels: documentation

#439 mainstem -> trunk
  configs/common/models/graph.py
Labels: bug
