Repository Oneflow-Inc/libai, pull requests merged in 2022-09, with the labels that each got.

#385 Align accuracy for MAE finetune
  libai/data/build.py
  libai/models/utils/graph_base.py
  projects/MAE/configs/mae_finetune.py
  projects/MAE/train_net.py
  projects/MAE/utils/lr_decay.py
  projects/MAE/utils/scheduler.py
  projects/MAE/utils/weight_convert.py
Labels: enhancement, ready for review

#389 Remove manual setting genrator in droppath
  configs/swin_imagenet.py
  libai/layers/droppath.py
  tools/train_net.py
Labels: bug

#396 update auto_parallel interface
  configs/common/models/graph.py
  docs/source/tutorials/basics/Auto_Parallel.md
  libai/models/utils/graph_base.py
Labels: enhancement
